version: '3'
services:

  mysql:
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - ${APPLICATION_NAME}-db:/var/lib/mysql
  # schema:
  #   image: dhoer/flyway
  #   ulimits:
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   command: -url=jdbc:mysql://mysql/${MYSQL_DATABASE_NAME} -user=${MYSQL_USERNAME} -password=${MYSQL_PASSWORD} migrate
  #   volumes:
  #     - "database/migrations:/flyway/sql:ro"
  #   depends_on:
  #     - mysql 
  #   restart: on-failure

volumes:
  test-api-db:s