version: '3.9'
services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - ${APPLICATION_NAME}-db:/var/lib/mysql

volumes:
  test-api-db: